#!/usr/bin/env python3
"""v0.11: Regenerate /etc/llm-manager/litellm_config.yaml from the model registry
+ hosts table. Run after model hosting changes and on a timer.

Source of truth = llmmanager DB (hosts + model_registry + manager_settings).
Backup of previous config is written next to it before overwrite.

Design (plan §C/F4/G):
- one LiteLLM model_name entry per (routable backend, logical model)
- local backends get explicit api_base; engine prefix openai/<served-name>
- OpenRouter fallback entry preserved (governed by spend_guard + caps)
- llamacpp host keeps its existing served name

After writing the config this script:
  1. validates YAML parses
  2. writes backup
  3. atomically replaces the live config
  4. signals LiteLLM to reload (systemctl restart litellm)

Run manually or from a systemd timer every 5 minutes.
"""
import os
import sys
import shutil
import tempfile

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import yaml  # noqa: E402
from v011_core import pg, NODE_MAP  # noqa: E402

CONFIG_PATH = "/etc/llm-manager/litellm_config.yaml"
HEADER = """# AUTO-GENERATED by v0.11 litellm_sync.py — DO NOT hand-edit.
# Source of truth: llmmanager DB (hosts + model_registry).
# Regenerate: python3 /opt/llm-manager/app/litellm_sync.py
"""


def load_current():
    with open(CONFIG_PATH) as f:
        return yaml.safe_load(f)


def build_model_list(conn):
    with conn.cursor() as cur:
        cur.execute("""SELECT r.logical_model_name, h.guest_ip, r.engine
                       FROM model_registry r JOIN hosts h ON h.host_id = r.host_id
                       WHERE r.routable = TRUE AND r.is_alias = FALSE
                       ORDER BY h.guest_ip, r.logical_model_name""")
        rows = cur.fetchall()
        cur.execute("""SELECT key, value FROM manager_settings
                       WHERE key IN ('openrouter.fallback_enabled')""")
        settings = dict(cur.fetchall())
    models = []
    seen = set()
    for name, ip, engine in rows:
        key = (name, ip)
        if key in seen:
            continue
        seen.add(key)
        local_alias = {"10.0.20.161": "local-00111", "10.0.20.162": "local-00112",
                       "10.0.20.163": "local-00143", "10.0.20.164": "local-00144",
                       "10.0.20.165": "dummy-local-llamacpp"}.get(ip, f"local-{ip}")
        rpm = 30 if engine == "llamacpp" else 300
        models.append({
            "model_name": name,
            "litellm_params": {
                "model": f"openai/{name}",
                "api_base": f"http://{ip}:8000/v1",
                "api_key": local_alias,
                "rpm": rpm,
            },
        })

    # §22 role aliases: `fast` / `code` / `frontier` map to the production
    # deployment of each tier. Alias is routable iff its target is.
    with conn.cursor() as cur:
        cur.execute("""SELECT logical_model_name, alias_target FROM model_registry
                       WHERE is_alias = TRUE AND routable = TRUE""")
        alias_rows = cur.fetchall()
        cur.execute("""SELECT r.logical_model_name, h.guest_ip FROM model_registry r
                       JOIN hosts h ON h.host_id = r.host_id
                       WHERE r.routable = TRUE AND r.is_alias = FALSE
                       ORDER BY r.logical_model_name, h.guest_ip""")
        target_backends = cur.fetchall()
    for alias, target in alias_rows:
        backends = [(n, ip) for n, ip in target_backends if n == target]
        for n, ip in backends[:1]:  # primary backend only; health gating picks winner
            local_alias = {"10.0.20.161": "local-00111", "10.0.20.162": "local-00112",
                           "10.0.20.163": "local-00143", "10.0.20.164": "local-00144",
                           "10.0.20.165": "dummy-local-llamacpp"}.get(ip, f"local-{ip}")
            models.append({
                "model_name": alias,
                "litellm_params": {
                    "model": f"openai/{n}",
                    "api_base": f"http://{ip}:8000/v1",
                    "api_key": local_alias,
                    "rpm": 300,
                },
            })
    # keep OpenRouter fallback as an explicit entry (its own model_name)
    if str(settings.get("openrouter.fallback_enabled", "true")).lower() == "true":
        models.append({
            "model_name": "openrouter/glm-5.3-flash",
            "litellm_params": {
                "model": "openrouter/z-ai/glm-5.3-flash",
                "api_key": "os.environ/OPENROUTER_API_KEY",
            },
        })
        # 2026-09-20 70K migration fallback: provider-backed DeepSeek V4.1 Flash.
        # Explicit entries only; no silent fallback from local Qwen aliases.
        for model_name in ("deepseek-v4.1-flash-api", "frontier"):
            models.append({
                "model_name": model_name,
                "litellm_params": {
                    "model": "openrouter/deepseek/deepseek-v4.1-flash",
                    "api_key": "os.environ/OPENROUTER_API_KEY",
                    "rpm": 60,
                },
            })
    return models


def main(apply=True):
    cur_cfg = load_current()
    conn = pg()
    if not conn:
        print("pg unavailable; not touching config", flush=True)
        return 1
    try:
        models = build_model_list(conn)
    finally:
        conn.close()

    fallbacks = []
    # route-level fallback: startupteams/general retired; per-model fallbacks only
    if any(m["model_name"].startswith("openrouter/") for m in models):
        pass  # no automatic cross-model fallback (plan §D: no silent substitution)

    new_cfg = {
        "model_list": models,
        "litellm_settings": {
            "drop_params": True,
            "num_retries": 1,
            "request_timeout": 600,
            "callbacks": ["spend_guard.spend_guard_instance",
                          "routing_logger.routing_logger_instance"],
        },
        "general_settings": cur_cfg.get("general_settings", {}),
    }

    rendered = HEADER + yaml.safe_dump(new_cfg, sort_keys=False, default_flow_style=False)
    # validation: parse what we are about to write
    yaml.safe_load(rendered)

    if not apply:
        print(rendered)
        return 0

    backup = CONFIG_PATH + ".bak.v011." + str(int(os.path.getmtime(CONFIG_PATH)))
    if not os.path.exists(backup):
        shutil.copy2(CONFIG_PATH, backup)
    fd, tmp = tempfile.mkstemp(dir=os.path.dirname(CONFIG_PATH))
    with os.fdopen(fd, "w") as f:
        f.write(rendered)
    os.chmod(tmp, 0o640)
    os.replace(tmp, CONFIG_PATH)
    print(f"config written ({len(models)} model entries); backup: {backup}", flush=True)
    return 0


if __name__ == "__main__":
    sys.exit(main(apply="--dry-run" not in sys.argv))
