"""arm initial schema

Revision ID: a73a833b72d1
Revises: 
Create Date: 2026-09-27 21:18:31.409083

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'a73a833b72d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runtimes',
    sa.Column('runtime_id', sa.UUID(), nullable=False),
    sa.Column('acms_agent_id', sa.String(length=64), nullable=False),
    sa.Column('provisioning_request_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('node', sa.String(length=40), nullable=True),
    sa.Column('vmid', sa.Integer(), nullable=True),
    sa.Column('harness', sa.String(length=40), nullable=False),
    sa.Column('runtime_class', sa.String(length=40), nullable=False),
    sa.Column('site', sa.String(length=40), nullable=False),
    sa.Column('model_route', sa.String(length=80), nullable=True),
    sa.Column('desired_state', sa.Enum('DESIRED_RUNNING', 'DESIRED_STOPPED', 'DESIRED_DESTROYED', name='arm_runtime_desired_state'), nullable=False),
    sa.Column('actual_state', sa.Enum('ABSENT', 'PROVISIONING', 'RUNNING', 'STOPPED', 'ERROR', 'DESTROYED', name='arm_runtime_actual_state'), nullable=False),
    sa.Column('created_by_agent_runtime_manager', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('template_source', sa.String(length=120), nullable=True),
    sa.Column('ownership_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hermes_state_repo', sa.String(length=120), nullable=True),
    sa.Column('hermes_state_branch', sa.String(length=120), nullable=True),
    sa.Column('hermes_profile_name', sa.String(length=120), nullable=True),
    sa.Column('last_state_commit_sha', sa.String(length=64), nullable=True),
    sa.Column('state_sync_health', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('runtime_id')
    )
    op.create_index(op.f('ix_agent_runtimes_acms_agent_id'), 'agent_runtimes', ['acms_agent_id'], unique=False)
    op.create_index(op.f('ix_agent_runtimes_provisioning_request_id'), 'agent_runtimes', ['provisioning_request_id'], unique=False)
    op.create_index(op.f('ix_agent_runtimes_vmid'), 'agent_runtimes', ['vmid'], unique=False)
    op.create_table('runtime_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('runtime_id', sa.UUID(), nullable=True),
    sa.Column('correlation_id', sa.String(length=80), nullable=True),
    sa.Column('actor', sa.String(length=60), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runtime_events_correlation_id'), 'runtime_events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_runtime_events_runtime_id'), 'runtime_events', ['runtime_id'], unique=False)
    op.create_table('bridge_registrations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('runtime_id', sa.UUID(), nullable=False),
    sa.Column('acms_agent_id', sa.String(length=64), nullable=False),
    sa.Column('bridge_credential_id', sa.String(length=80), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['runtime_id'], ['agent_runtimes.runtime_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('runtime_id', 'acms_agent_id', name='uq_bridge_reg_runtime_agent')
    )
    op.create_index(op.f('ix_bridge_registrations_acms_agent_id'), 'bridge_registrations', ['acms_agent_id'], unique=False)
    op.create_table('provisioning_jobs',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('runtime_id', sa.UUID(), nullable=False),
    sa.Column('requested_by', sa.String(length=60), nullable=False),
    sa.Column('authority', sa.String(length=60), nullable=False),
    sa.Column('state', sa.Enum('QUEUED', 'RUNNING', 'DONE', 'FAILED', 'CANCELLED', name='arm_job_state'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['runtime_id'], ['agent_runtimes.runtime_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index(op.f('ix_provisioning_jobs_request_id'), 'provisioning_jobs', ['request_id'], unique=True)
    op.create_table('provisioning_steps',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('step', sa.String(length=60), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['provisioning_jobs.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'seq', name='uq_provstep_job_seq')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('provisioning_steps')
    op.drop_index(op.f('ix_provisioning_jobs_request_id'), table_name='provisioning_jobs')
    op.drop_table('provisioning_jobs')
    op.drop_index(op.f('ix_bridge_registrations_acms_agent_id'), table_name='bridge_registrations')
    op.drop_table('bridge_registrations')
    op.drop_index(op.f('ix_runtime_events_runtime_id'), table_name='runtime_events')
    op.drop_index(op.f('ix_runtime_events_correlation_id'), table_name='runtime_events')
    op.drop_table('runtime_events')
    op.drop_index(op.f('ix_agent_runtimes_vmid'), table_name='agent_runtimes')
    op.drop_index(op.f('ix_agent_runtimes_provisioning_request_id'), table_name='agent_runtimes')
    op.drop_index(op.f('ix_agent_runtimes_acms_agent_id'), table_name='agent_runtimes')
    op.drop_table('agent_runtimes')
    # ### end Alembic commands ###
